### PR TITLE
GIVCAMP-67 | Page transition test

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch or go to the netlify preview
2. Navigate to...
3. Verify...

# Associated Issues and/or People
- JIRA ticket(s) - GIVCAMP-
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama What you asked for - page transition 😄 
Click on first card in the Dark section to go to an internal page, then click logo to go back to home page to test
https://deploy-preview-24--giving-campaign.netlify.app/

**Comment by sherakama** [comment]
Yeah, you should share this explore as you may be able to sell it to the stakeholders.

**Comment by yvonnetangsu** [comment]
FYI I'm still leaving this open because I'm saving it only for when we really need it. I feel like the page transition might be a bit too much 😂

**Comment by yvonnetangsu** [comment]
Closing this as this is the Gatsby approach and I think it's a bit of an overkill anyhow 🤣

**Pull request closed without merging**
