### PR TITLE
GIVCAMP-273: Remove asset proxy URL.

### PR DESCRIPTION
**Pull request by sherakama**
# NOT READY FOR REVIEW

# Summary
- Removing one layer of complexity

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch or go to the netlify preview
2. Navigate to...
3. Verify...

# Associated Issues and/or People
- JIRA ticket(s) - GIVCAMP-
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

### CODE REVIEW

**Comment by sherakama** [comment]
@yvonnetangsu so, it looks like nothing resolves when you remove the proxy... WTH?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu so, it looks like nothing resolves when you remove the proxy... WTH?

Yeah this is really weird 🤔

The image loading issue seems to be fairly recent as well. I don't remember seeing that delay (or image not loading) before. I wonder if it has to do with all the Storyblok changes recently (not sure if they're changing anything under the hood)

**Comment by yvonnetangsu** [comment]
> > @yvonnetangsu so, it looks like nothing resolves when you remove the proxy... WTH?
> 
> Yeah this is really weird 🤔
> 
> The image loading issue seems to be fairly recent as well. I don't remember seeing that delay (or image not loading) before. I wonder if it has to do with all the Storyblok changes recently (not sure if they're changing anything under the hood)

That might be related to this actually in next config
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'assets.stanford.edu',
      },

**Comment by yvonnetangsu** [comment]
I thought it's only for when you use Next Image, but I guess I remember it wrong 🤔

**Comment by sherakama** [comment]
> > > @yvonnetangsu so, it looks like nothing resolves when you remove the proxy... WTH?
> > 
> > Yeah this is really weird 🤔
> > 
> > The image loading issue seems to be fairly recent as well. I don't remember seeing that delay (or image not loading) before. I wonder if it has to do with all the Storyblok changes recently (not sure if they're changing anything under the hood)
> 
> That might be related to this actually in next config
>   images: {
>     remotePatterns: [
>       {
>         protocol: 'https',
>         hostname: 'assets.stanford.edu',
>       },

I added a-us.storyblok to the config. Also, you can't directly navigate to the images on the service which has nothing to do with next or Netlify

**Comment by yvonnetangsu** [comment]
> > > > @yvonnetangsu so, it looks like nothing resolves when you remove the proxy... WTH?
> > > 
> > > 
> > > Yeah this is really weird 🤔
> > > The image loading issue seems to be fairly recent as well. I don't remember seeing that delay (or image not loading) before. I wonder if it has to do with all the Storyblok changes recently (not sure if they're changing anything under the hood)
> > 
> > 
> > That might be related to this actually in next config
> > images: {
> > remotePatterns: [
> > {
> > protocol: 'https',
> > hostname: 'assets.stanford.edu',
> > },
> 
> I added a-us.storyblok to the config. Also, you can't directly load the images on the service which has nothing to do with next or Netlify

Hmmmm definitely weird...... it was definitely not like that before, because it worked at one point before I added the getMaskedUrl function 😂 

Ok out to meet Dena and Andy for real. I'll be back later today to investigate with you.

**Comment by sherakama** [comment]
Seems to be working again. I'm going to point the finger of blame at Storyblok for this one.

**Comment by yvonnetangsu** [comment]
> Seems to be working again. I'm going to point the finger of blame at Storyblok for this one.

Thanks for investigating, @sherakama! I just posted in Discord too and see if they know anything.

**Pull request closed without merging**
