### PR TITLE
GIVCAMP-277: Revert "NoJira: Storyblok API Javascript client update to support fetch parameters

### PR DESCRIPTION
**Pull request by sherakama**
#  READY FOR REVIEW

# Summary
- Reverts back to killing the data cache on the server filesystem instead of trying to set the no-store on the fetch
- I'm punting on this as it looks like we are in a bit of a pickle and I've banged on this enough already. Looking at the threads there looks to be a couple of issues open with the datacache and static -> dynamic navigation. 
- I'd like to revisit this after the Netlify Next plugin update.
- Reverts: https://github.com/SU-SWS/ood-giving-campaign/pull/192

Issues:
* https://github.com/vercel/next.js/issues/43879
* https://github.com/vercel/next.js/issues/46737
* https://github.com/vercel/next.js/issues/42991
* https://github.com/vercel/storage/issues/213

# Review By (Date)
- When you'd like

# Criticality
- Regular

# Review Tasks

1. Review code
2. Review preview build

### CODE REVIEW

**Comment by sherakama** [comment]
🤔 Hmmm.. No 500.

**Comment by yvonnetangsu** [comment]
> 🤔 Hmmm.. No 500.

So weird..... 😬

**Review by yvonnetangsu — APPROVED** [review]
GTG - thank you for your patience @sherakama! 😆

**Comment by sherakama** [comment]
> I've tried updating to the latest @storyblok/react 3.0.8 

Yeah, I looked at the changed and it is just minor package updates for dependencies and doesn't address this issue.

**Pull request merged**
