### PR TITLE
Release/release v0.0.1

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- Initial release of everything from PR #11 to PR #40 and to test release workflow

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at code and preview

# Associated Issues and/or People
- JIRA ticket(s) - GIVCAMP-24

### CODE REVIEW

**Comment by sherakama** [comment]
This looks fine but your resulting release version will be `0.0.2` as the current version in package.json is `0.0.1`

If you want to release `0.0.1` change the version value in `package.json` to `0.0.0`

**Comment by yvonnetangsu** [comment]
> This looks fine but your resulting release version will be `0.0.2` as the current version in package.json is `0.0.1`
> 
> If you want to release `0.0.1` change the version value in `package.json` to `0.0.0`

Oh yeah I shall do that - thanks Shea!

**Comment by yvonnetangsu** [comment]
Merging this in and crossing my fingers 🤞🏼

**Comment by sherakama** [comment]
@yvonnetangsu looks like the release failed and it looks likely to do with the GH access token. I've updated it, you should be able to try again.

**Comment by yvonnetangsu** [comment]
Thanks @sherakama 👍🏼 Yeah I just saw that you updated it there too - 🤣  Thank you! I'll also push a commit to actually include a release drafter. I'm guessing I should change the version in package.json back to 0.0.0 too 🤔 ?

**Pull request merged**
