### PR TITLE
Release/v2.2.2

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #303 
- #306 
- #307 

# Review By (Date)
- Soon

# Criticality
- 5

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at the preview and check that everything is working as expected

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama I have tested multiple things - on mobile, embedded media, typeform, Safari, reduced motion, framer motion, storyblok editor, and everything seems to be functioning as normal. If you could do a quick scan and make sure this is good to go, that'd be awesome 😄

**Comment by yvonnetangsu** [comment]
I'm going to hold off on merging this. Alexis just ping me for an option to change out a background image for the homepage. I'll bundle that into this release 😄

**Comment by yvonnetangsu** [comment]
@sherakama Talked to Alexis and changed my mind. We're not ready to go live with #309 until July 17, so this release can go out without that PR merged in.

**Review by sherakama — APPROVED** [review]
GTG. Thank you for the updates.

**Comment by yvonnetangsu** [comment]
Thank you @sherakama ! I'll push it live while you're still here in case things fall apart 😆 🤠

**Pull request merged**
