### PR TITLE
Nojira | Add release-drafter.yml

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- Add release-drafter.yml file for the release workflow (turns out I need this or it holds up the release workflow 😬 )

# Review Tasks

## Setup tasks and/or behavior to test

1. 

# Associated Issues and/or People
- JIRA ticket(s) - GIVCAMP-24

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama LMK if I should be doing this 😬 🍤

**Review by sherakama — APPROVED** [review]
sure, formats your output. Not required but it will stay consistent with the other stuff we have.

**Comment by yvonnetangsu** [comment]
@sherakama I re-run the failed GitHub action, and it created the tag 0.0.1 (but not as a release) - is it because there wasn't a release drafter there when the release branch was merged? In this current PR, should I stick with version 0.0.1 or change it back to 0.0.0? 🤔  Thanks for your help!

**Comment by yvonnetangsu** [comment]
Ahh looks like I can create a release from a tag in the GitHub UI...interesting 👀 Learn something new everyday

**Comment by yvonnetangsu** [comment]
Screenshot 2023-04-26 at 1 56 51 PM

Hmmm

**Comment by yvonnetangsu** [comment]
I'm going to try again 🤠

**Pull request merged**
